### PR TITLE
Found a few strange methods

### PR DESCRIPTION
**Pull request by ivanpopelyshev**
Fixes related to "mine" parts of pixi. Its scary parts for most of our coders :)

TextureTransforms fixes: I wrote this class, I know what is public here!
GroupD8: yeah, one of methods was renamed some time ago.

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
btw, TextureTransform will be renamed if this thing merges: https://github.com/pixijs/pixi.js/pull/4357

**Comment by clark-stevenson** [comment]
Thanks Ivan 💃 

I will try to catch my open DT commit and leave this open until I know what happens with that rename.

**Comment by clark-stevenson** [comment]
It breaks one of the tests (examples) which still reference `isSwapWidthHeight`

https://github.com/pixijs/examples/blob/gh-pages/required/examples/demos/texture-rotate.js#L20

I got rid of this test for Definitely Typed but not here yet.  Should I open a ticket there?

**Comment by ivanpopelyshev** [comment]
!@#$ I forgot to change it to isVertical in pixi itself, i looked in one of branches. Sorry, removing it for a bit.

**Comment by clark-stevenson** [comment]
Will I undo these changes for now? My DT PR is still open.

**Comment by clark-stevenson** [comment]
Its just been merged 😄 Funny how it often can take days unless there is a mistake.

**Pull request merged**
