### PR TITLE
Fixed typos in BlurFilter definitions.

### PR DESCRIPTION
**Pull request by Adamfsk**

### CODE REVIEW

**Comment by englercj** [comment]
Good catch, can you please send PRs to the `dev` branch?

**Comment by clark-stevenson** [comment]
There is no dev branch as there are no releases at this time.

**Comment by clark-stevenson** [comment]
I wanted to expand on this a bit more but was unable before. 

For me at the moment, this is experimental. I need these definitions and so without them existing, I cannot even access the library to make any tests to try out how cool it is. 

What we have now is kind of a first pass powered by beer, and then a bunch of tests which helped a lot! But still tons of the library remains untested.  Everyone with a Pixi typescript project validates the pixi.d.ts and the user base is small and my tests zero.....

Over the next wee while, I would say any PR matching the dev branch of pixi is good to go, the reviews of the commit history will continue and sometime soon there will be something stable. It would be then I would think about hitting versions on it. 

But honestly Chad, I am pretty out of my depth here when it comes to the structure of this repo or how things should be done best practice. I just wanted to share my intent and see your thoughts.

**Comment by Adamfsk** [comment]
Hey Clark, based on his asking for a dev branch, I think Chad might be expecting the git flow workflow or something similar. If you're using SourceTree then it's easy to set up Git Flow - open the repo in SourceTree and click the Git Flow button. Otherwise, there's a tutorial on what you need to download/what commands you need to work with here: http://yakiloo.com/getting-started-git-flow/

**Comment by clark-stevenson** [comment]
Thank you @Adamfsk ! That kind of thing was exactly what I needed and I appreciate the sourcetree reference because I use it so this will get me started. https://github.com/GSoft-SharePoint/Dynamite/wiki/Getting-started-with-SourceTree,-Git-and-git-flow added to my todo!

**Comment by englercj** [comment]
My god, Im so stupid!

I thought this was pixi, not the typescript repo! So sorry!!!

**Pull request closed without merging**
