### PR TITLE
Allow to use fluent interface for event listeners.

### PR DESCRIPTION
**Pull request by evgeniy-polyakov**
Code like `PIXI.loader.add('url-to-load').on('error', ()=>{}).load();` should be valid.

### CODE REVIEW

**Review by ivanpopelyshev — APPROVED** [review]
nice one

**Comment by ivanpopelyshev** [comment]
Are you using pixi much?

**Comment by clark-stevenson** [comment]
Thanks 😄

**Comment by evgeniy-polyakov** [comment]
Not so much, only for my game project. But I love typescript and its power :)

**Comment by ivanpopelyshev** [comment]
If you use slack to participate in open-source projects, you can send me an email to ivan.popelyshev@gmail.com and I'll invite you to pixijs slack. We already have 10 people in #russian channel

**Pull request merged**
