### PR TITLE
Constructors are called constructors, not new.

### PR DESCRIPTION
**Pull request by webbiesdk**

### CODE REVIEW

**Comment by webbiesdk** [comment]
I can see that this is confusing. 
Since constructors are called "new" when they are in an interface. 
But they are called "constructor" when they are inside a class.

**Comment by clark-stevenson** [comment]
@webbiesdk 

I was scared of the whole module and a gentleman from here added it I think.  I was really surprised by `new` even being there and not throwing any issues. 

Is what you just said how TypeScript is supposed to work by design?

**Comment by webbiesdk** [comment]
Yes it is how TypeScript works, although I get a little warning when using "new" inside a class declaration. 
Lets look at an example, which although being nasty, is valid TypeScript. 

``` TypeScript
interface MyInterface {
    new(): MyKlass; // 1
    new: () => RegExp; // 2
    constructor(): Array; // 3
}

declare class MyKlass {
    constructor(); // 4 (does the same as 1)
    new(): RegExp; // 5  (does the same as 2)
    constructor: () => Array; // 6  (does the same as 3) 
}
```

The way IntelliJ syntax highlights it makes my point clearer: http://i.imgur.com/Frpdrg3.png (the blue fields are the actual constructors). 

I will now explain what each of the lines 1 through 6 actually do. 
1 and 4 declares an actual constructor, that can be called with the `new` operator, and returns a MyKlass. 
2 and 5 declares a method "new", which when called returns a RegExp. 
3 and 6 declares a method "constructor", which when called returns an Array. 

So yeah, inside a class the keyword "constructor" does the same thing as the keyword "new" does inside an interface.

**Comment by clark-stevenson** [comment]
Thanks for taking the time to explain that @webbiesdk , had to read it a couple of times to wrap my head around it.

**Pull request merged**
