### PR TITLE
Fix filterArea type

### PR DESCRIPTION
**Pull request by Icemic**
fix filterArea declare.

Ref: http://pixijs.download/release/docs/core_display_DisplayObject.js.html#line91

### CODE REVIEW

**Comment by clark-stevenson** [comment]
@Icemic 

Thanks for PR 👍 

Do we need the explicit null?  If this isn't set, isn't it null or undefined anyway?

**Comment by ivanpopelyshev** [comment]
Its null by default.

**Comment by clark-stevenson** [comment]
So i am pretty sure we don't need it.   From a TS definition perspective, what you are accessing is the property type.  Whether it is null at runtime or not is a different matter.  If this becomes `null` then pretty much everything else which could be null would need typed for consistency.

Thanks anyway though 👍

**Comment by Icemic** [comment]
But, it throws error when I try to set alphaArea to null to cancel area setting. Or is there another way to cancel alphaArea setting?

**Comment by clark-stevenson** [comment]
@Icemic you were right! I think it is related to an option `strictNullCheck` which was also a problem on issue 195

**Comment by clark-stevenson** [comment]
Will be part of DT soon https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23545

Thanks again 👍

**Comment by Icemic** [comment]
Glad to contribute!

**Pull request merged**
