### PR TITLE
Correct typing for filter uniforms

### PR DESCRIPTION
**Pull request by giraluna**
Typings for Filter.uniformData and 'uniforms' param in Filter constructor were wrong.

Filter class could be made generic to preserve typing for uniforms, but as generics aren't used elsewhere in the typings, I left them partially untyped for consistency's sake.

(Does this merge properly with #108 ? I thought splitting them up would be good for clarity but who knows.)

### CODE REVIEW

**Comment by clark-stevenson** [comment]
Awesome thanks @giraluna  👍

**Comment by ivanpopelyshev** [comment]
yep, basically , uniforms are MAP of something, and sometimes they do have structures inside ;)

That's one of things in PIXI that cant be used with types, one of exclusive javascript features.

**Comment by giraluna** [comment]
You can preserve typing for uniforms by extending the base class. Example:

```
class BlurFilter extends PIXI.Filter {
  uniforms: {blurStrength: number};
}

const blur = new BlurFilter();
blur.uniforms.red = 1; // error
```

The problem is that the base Filter class can't have strict typing without using generics. This can lead to bugs while writing the derived class. Maybe it'd be better just to define Filter as a generic class.

**Comment by clark-stevenson** [comment]
Ah thanks, I always wondered what uniforms actually were as at the time, the docs were inconsistent.

So @giraluna does it mean we would use `any` for filter?

**Comment by giraluna** [comment]
There shouldn't be a need to use any, except for the uniform values which can have arbitrary structs like @ivanpopelyshev said.

We could use generics to do something like:

```
type UniformValuesMap = {[name: string]: any};
type UniformDataMap = {[name: string]: IUniformData};

export class Filter<UniformValues extends UniformValuesMap, UniformData extends UniformDataMap> {

    constructor(vertexSrc?: string, fragmentSrc?: string, uniforms?: UniformData);
    protected uniformData: UniformData;
    uniforms: UniformValues;
    ...
```

Rather than relying on the user to override the type of uniforms in the derived class, this enforces that uniforms are always strictly typed:

```
type BlurUniformValues = {
  blurStrength: number;
};
const blurUniforms = {
  blurStrength: {type: "float", value: 3},
};

class BlurFilter extends PIXI.Filter<BlurUniformValues, typeof blurUniforms> {
  constructor() {
    super(vertexSrc, fragmentSrc, blurUniforms);
  }
}

const blur = new BlurFilter();
blur.uniforms.green += 0.1; // still an error
```

This would help people transitioning from pixi v3 to v4, as Filter.uniforms was changed to contain uniform values rather than uniform data. Because uniform values can be anything (even uniform data!), requiring strict typing via generics is the only way to catch the error of treating Filter.uniforms as uniform data.

**Pull request merged**
