### PR TITLE
changes returned object for some Container methods from DisplayObject…

### PR DESCRIPTION
**Pull request by bbruneau**
… to T extends DisplayObject

### CODE REVIEW

**Comment by bbruneau** [comment]
@clark-stevenson I found I was getting errors when accessing children of containers because a) they weren't `DisplayObject`s or b) `DisplayObject` didn't have xyz method or property.

**Comment by ivanpopelyshev** [comment]
I agree, that's a very good idea! What do you think @clark-stevenson ? we can add `= DisplayObject` there as a default param

**Comment by clark-stevenson** [comment]
Thanks @bbruneau  👍!

@ivanpopelyshev  where would you add that `= DisplayObject` ?

**Comment by ivanpopelyshev** [comment]
```
T extends DisplayObject = DisplayObject
```
or even better

```
T extends DisplayObject = Container
```

because that's what we always encounter there

**Pull request merged**
