### PR TITLE
Mark BaseTexture.loadSource as protected

### PR DESCRIPTION
**Pull request by giraluna**

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
@clark-stevenson I'm against adding extra protected fields. Let everything be public :)

**Comment by clark-stevenson** [comment]
@ivanpopelyshev 

Is that not quite annoying though as your API will be more messy in intelisense? You won't know just by typing if something is considered accessible or not. I find that intent quite valuable. 

I used to do only public methods (ignoring private/protected entirely), but one day, I was using phaser, and overridding a private method.  The pain of finding that bug was real bad.  So that is where they came from.

Anyone know the best practice on that?

**Comment by ivanpopelyshev** [comment]
I mean don't use "protected" word for them, leave them public. I just don't like hacks "(texture as any)._uvs"

**Comment by clark-stevenson** [comment]
Does that not point to an implementation problem though? If `uvs` in the example is intended to be used, it shouldn't be called `_uvs`,  it should be exposed in the API and there lies the problem?

I don't know by the way which is why I am asking.  I know that JavaScript treats everything as public, but if you start to take the definition down those roads, it starts to lose some of its value?

**Comment by giraluna** [comment]
[According to pixi docs it's protected.](https://github.com/pixijs/pixi.js/blob/dev/src/core/textures/BaseTexture.js#L262)

Shouldn't the definitions mirror the code/docs in pixi? If the definitions are accurate and you still have no choice but to work around the type system, the problem is in either pixi or typescript itself.

**Comment by ivanpopelyshev** [comment]
If you are using only upper pixi api, then sure, its protected. If you developing your own renderers, or your own loader, then all those fields must be accessible. I don't know what to do about that.

**Comment by giraluna** [comment]
I feel like there's essentially a need 2 separate definitions, one for the public interface and one for internals. I think the api meant to be consumed should be maintained as the source of truth with others derived from it.

I haven't tried them yet, but maybe you could use the new [mapped types from typescript 2.1](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#mapped-types) for exposing internals?

```
type Public<T> = {
  public [P in keyof T]: T[P];
}

const texture: Public<Texture> = ...
texture._uvs = ... // no warning?
```

(Edit) What I mean by requiring 2 separate definitions is:
Accessing inaccessible members is just fundamentally incompatible, so it's impossible to make an accurate definition that allows both. Not suggesting at all we maintain multiple definitions for the same thing.

**Comment by ivanpopelyshev** [comment]
oh, nice! thank you!

**Comment by clark-stevenson** [comment]
In any case, this seems correct! Thanks @giraluna  I will leave this open as an issue until I take a look at mapped types.  Thanks for the heads up!

**Pull request merged**
