### PR TITLE
Various small fixes, mostly related to strict nulls

### PR DESCRIPTION
**Pull request by webbiesdk**
I'm doing a thing were I run a library, and check if what comes out matches the TypeScript declaration file.

I used that to find some bugs in your declaration file. 

Most of them are related to strict-nulls (so this removes support for TypeScript less than 2.0, if you havn't already).

### CODE REVIEW

**Comment by clark-stevenson** [comment]
Thanks as always Webbie, sounds interesting but I don't fully understand how you got back to these results.   It sounds like some kind of automation from docs etc?

**Comment by webbiesdk** [comment]
> It sounds like some kind of automation from docs etc?

It is.

**Comment by clark-stevenson** [comment]
https://github.com/webbiesdk/tstools ?

**Comment by webbiesdk** [comment]
No, that one i used for all the fixes i sent you guys a while ago.

**Comment by webbiesdk** [comment]
The thing I'm doing now is not open source as of yet. It will be later.

**Comment by clark-stevenson** [comment]
Sounds amazing! Good luck with it 👍

**Pull request merged**
