### PR TITLE
Fix PIXI.TextStyle

### PR DESCRIPTION
**Pull request by lucap86**
Fix PIXI.TextStyle according to
https://pixijs.github.io/docs/PIXI.TextStyle.html

### CODE REVIEW

**Comment by ivanpopelyshev** [comment]
You mistook constructor params with fields. Those fields are copied inside TextStyle, there's no "public style". Yes, we can add ITextStyle and make TextStyle extend it.

**Review by ivanpopelyshev — CHANGES_REQUESTED** [review]
TextStyle must extends ITextStyle, and there's no "style" field, its a param of constructor

**Comment by lucap86** [comment]
My mistake, sorry.
done.
-TextStyle implements ITextStyle.
-Added constructor
-removed style as property

**Comment by clark-stevenson** [comment]
Looks good to me, thanks guys 👍

**Comment by ivanpopelyshev** [comment]
@clark-stevenson it wasn't good :) I just fixed it by making direct commit, please look at it.

**Pull request merged**
